### ISSUE TITLE
集群中节点数据为2，主机资源中只显示1个节点

### ISSUE THREAD

**Issue by lishijiang** [DTStack/chengying#10]
![image](https://user-images.githubusercontent.com/28666812/179726308-b8f2415b-f6fd-48a2-866c-949729fd8c1c.png)
![image](https://user-images.githubusercontent.com/28666812/179726406-b0842f7e-dee5-4099-a1eb-86d64a4428d5.png)

**Comment by wangqi811** [comment]
实际上接入了几台主机？

**Comment by lishijiang** [comment]
> 实际上接入了几台主机？

实际接入了2台

**Comment by wangqi811** [comment]
使用MySQL客户端登录数据库，用户名root，密码DT#passw0rd2019，看下dtagent库deploy_host表里面有没有这条不显示主机的记录，有的话就删掉

**Comment by lishijiang** [comment]
1、删除之后，页面查有报空值不能转的问题，看了一下接口，是以下sql查询报错的
SELECT deploy_host.id,mem_size,mem_usage,disk_usage,cpu_cores,cpu_usage,local_ip,deploy_host.status,deploy_host.updated FROM deploy_cluster_host_rel LEFT JOIN deploy_host ON deploy_cluster_host_rel.sid = deploy_host.sid LEFT JOIN sidecar_list ON sidecar_list.id = deploy_host.sid WHERE deploy_cluster_host_rel.clusterId = 2 and deploy_cluster_host_rel.is_deleted = 0；

2、把deploy_cluster_host_rel里对应的记录也删除，就没有问题了。

**Comment by wangqi811** [comment]
数据都清除掉之后现在可以正常接入主机了吗

**Comment by chenjunyu0103** [comment]
您好，我这边发现无法接入主机，我拷贝接入curl命令后，在页面上没有显示出来。
![image](https://user-images.githubusercontent.com/72799872/181151632-167744c8-7795-49cb-8cf9-2a3958d39d55.png)
查看了TargetPath发现里是空目录，是不是缺少什么二进制文件之类的

**Comment by lishijiang** [comment]
> 数据都清除掉之后现在可以正常接入主机了吗

正常了
