### ISSUE TITLE
部署hive时依赖mysql，不会自动识别出依赖的mysql地址，默认识别为127.0.0.1

### ISSUE THREAD

**Issue by lishijiang** [DTStack/chengying#12]
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/28666812/182750126-c6dcf4ba-9197-419c-9700-768ece4af6f2.png">

**Comment by wangqi811** [comment]
使用新包之后可以了吗

**Comment by lishijiang** [comment]
> 使用新包之后可以了吗

可以了，原因应该是hive包里定义依赖是mysql_metastore@Mysql.mysql@optional，而5.7.35版本，使用的产品名是MYSQL导致找不到？后续能否在页面上选择依赖服务，这样灵活性会更大的，特别是针对多实例部署这块，不用反复去上传产品包。

**Comment by wangqi811** [comment]
> > 使用新包之后可以了吗
> 
> 可以了，原因应该是hive包里定义依赖是mysql_metastore@Mysql.mysql@optional，而5.7.35版本，使用的产品名是MYSQL导致找不到？后续能否在页面上选择依赖服务，这样灵活性会更大的，特别是针对多实例部署这块，不用反复去上传产品包。

这个暂时还没有计划，因为考虑到本身产品包被制作出来到投入正式使用这个过程会比较固定，一般来说产品包制作完成之后不会再做轻易更改，针对灵活配置来说，页面也是可以编辑依赖服务的ip的，所以使用上不会有阻塞性问题产生。

如果个人有需求的话可以基于我们的代码二开或者给我们提PR~
