### ISSUE TITLE
已经接入集群的主机，状态为运行中，如何剔除

### ISSUE THREAD

**Issue by mxloveluc** [DTStack/chengying#14]
![image](https://user-images.githubusercontent.com/45912214/187113970-0df7ed16-7be5-42a8-832c-beeca06ba15e.png)
我想剔除这些主机，点击下架
![image](https://user-images.githubusercontent.com/45912214/187114044-8ab4147a-0c91-4405-8564-05c244c8df67.png)
请问如何剔除

**Comment by wangqi811** [comment]
参考 https://dtstack.github.io/chengying-web/docs/chengyingDocs/faq/
