### ISSUE TITLE
您好！请问我的agent为什么一直报错，添加主机页面无显示，数据库中有添加的主机信息,sid列为空。

### ISSUE THREAD

**Issue by yrui319** [DTStack/chengying#18]
* * * chengying-server端日志 * * * 
MATRIX-DEBUG:2022/11/25 21:04:55 cluster.go:2192: [Cluster->GetHostClusterList] GetHostClusterList from EasyMatrix API 
MATRIX-DEBUG:2022/11/25 21:04:55 cluster.go:2771: HostGroups: /api/v2/cluster/hostgroups?type=hosts&id=23
MATRIX-DEBUG:2022/11/25 21:04:58 cluster.go:2771: HostGroups: /api/v2/cluster/hostgroups?type=hosts&id=23
MATRIX-DEBUG:2022/11/25 21:04:58 cluster.go:2192: [Cluster->GetHostClusterList] GetHostClusterList from EasyMatrix API 
MATRIX-DEBUG:2022/11/25 21:04:59 agent.go:224: [CheckPwdConnect] check ssh connect by user password from EasyMatrix API 
MATRIX-DEBUG:2022/11/25 21:04:59 agent.go:129: [skip exist cluster]%!(EXTRA *errors.errorString=sql: no rows in result set)
MATRIX-DEBUG:2022/11/25 21:05:01 cluster.go:2192: [Cluster->GetHostClusterList] GetHostClusterList from EasyMatrix API 
MATRIX-DEBUG:2022/11/25 21:05:01 cluster.go:2771: HostGroups: /api/v2/cluster/hostgroups?type=hosts&id=23
MATRIX-DEBUG:2022/11/25 21:05:03 agent.go:284: [AgentInstallByPwd] install agent by user password from EasyMatrix API 
MATRIX-DEBUG:2022/11/25 21:05:03 agent.go:299: * * * AgentInstallByPwd * * * ctx -> &{0xc001815380 0xc001864b00 {[]} [{userId 2 false} {username admin@hh.com false} {expiration {0 63805237107 0x3d7e0c0} false}] 0xc0018d84d0 [0x9b28a0] <nil> 0}
MATRIX-DEBUG:2022/11/25 21:05:03 agent.go:300: * * * AgentInstallByPwd * * * params -> &{{172.21.0.15 22 root Datasphere#12345! } 23 hosts  }
MATRIX-DEBUG:2022/11/25 21:05:03 agent.go:327: * * * execAgentInstallByPwd * * * info -> &{0    0 0  0 {0 0 <nil>} {0 0 <nil>}  { false}}
MATRIX-DEBUG:2022/11/25 21:05:03 agent.go:373: * * * execAgentInstallByPwd * * * 373
MATRIX-DEBUG:2022/11/25 21:05:03 agent.go:118: GetAgentInstallCmd: curl -s 'http://127.0.0.1:8889/api/v1/deploy/sidecar/install/shell?TargetPath=/opt/dtstack/easymanager/easyagent&CallBack=aHR0cDovLzgyLjE1Ny4yNi4xNTI6ODA5OS9hcGkvdjIvYWdlbnQvaW5zdGFsbC9jYWxsYmFjaz9haWQ9MTk=&Type=hosts&ClusterId=23&Roles=' | sh
MATRIX-DEBUG:2022/11/25 21:05:03 agent.go:399: * * * execAgentInstallByPwd * * * 399
MATRIX-DEBUG:2022/11/25 21:05:04 cluster.go:2771: HostGroups: /api/v2/cluster/hostgroups?type=hosts&id=23
MATRIX-DEBUG:2022/11/25 21:05:04 cluster.go:2192: [Cluster->GetHostClusterList] GetHostClusterList from EasyMatrix API 
MATRIX-DEBUG:2022/11/25 21:05:07 cluster.go:2192: [Cluster->GetHostClusterList] GetHostClusterList from EasyMatrix API 
MATRIX-DEBUG:2022/11/25 21:05:07 cluster.go:2771: HostGroups: /api/v2/cluster/hostgroups?type=hosts&id=23
MATRIX-DEBUG:2022/11/25 21:05:10 agent.go:435: * * * AgentInstallByPwd * * * resBody -> map[result:[+] Installing agent (easyagent sidecar)...
Stopping easyagent-sidecar
27370
Killing easyagent-sidecar (pid 27370) with SIGTERM
Waiting easyagent-sidecar (pid 27370) to die...
Waiting easyagent-sidecar (pid 27370) to die...
easyagent-sidecar stopped stopped
[+] config EasyManage agent (easyagent sidecar)...
[+] easyagent-sidecar is already installed...
[+] setting EasyManage agent (easyagent sidecar)...
Starting easyagent-sidecar
started
start easyagent success! ...
]
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 

* * * agent-server端日志 * * *
==> easyagent-server.log <==
EA-SERVER-DEBUG:2022/11/25 21:05:03 ssh.go:125: RunWithUserPwd:&{172.21.0.15 22 root Datasphere#12345!  1 curl -s 'http://127.0.0.1:8889/api/v1/deploy/sidecar/install/shell?TargetPath=/opt/dtstack/easymanager/easyagent&CallBack=aHR0cDovLzgyLjE1Ny4yNi4xNTI6ODA5OS9hcGkvdjIvYWdlbnQvaW5zdGFsbC9jYWxsYmFjaz9haWQ9MTk=&Type=hosts&ClusterId=23&Roles=' | sh}
EA-SERVER-DEBUG:2022/11/25 21:05:03 manage.go:106: * * * RunWithSSH * * * params -> &{172.21.0.15 22 root Datasphere#12345!  1 curl -s 'http://127.0.0.1:8889/api/v1/deploy/sidecar/install/shell?TargetPath=/opt/dtstack/easymanager/easyagent&CallBack=aHR0cDovLzgyLjE1Ny4yNi4xNTI6ODA5OS9hcGkvdjIvYWdlbnQvaW5zdGFsbC9jYWxsYmFjaz9haWQ9MTk=&Type=hosts&ClusterId=23&Roles=' | sh}
EA-SERVER-DEBUG:2022/11/25 21:05:03 manage.go:107: * * * RunWithSSH * * * sync -> true
EA-SERVER-DEBUG:2022/11/25 21:05:03 manage.go:75: * * * runWithSSH * * * param -> &{172.21.0.15 22 root Datasphere#12345!  1 curl -s 'http://127.0.0.1:8889/api/v1/deploy/sidecar/install/shell?TargetPath=/opt/dtstack/easymanager/easyagent&CallBack=aHR0cDovLzgyLjE1Ny4yNi4xNTI6ODA5OS9hcGkvdjIvYWdlbnQvaW5zdGFsbC9jYWxsYmFjaz9haWQ9MTk=&Type=hosts&ClusterId=23&Roles=' | sh}
EA-SERVER-DEBUG:2022/11/25 21:05:03 manage.go:76: * * * runWithSSH * * * sync -> true
EA-SERVER-DEBUG:2022/11/25 21:05:03 client.go:62: * * * CreateWithParam * * * param -> &{172.21.0.15 22 root Datasphere#12345!  1 curl -s 'http://127.0.0.1:8889/api/v1/deploy/sidecar/install/shell?TargetPath=/opt/dtstack/easymanager/easyagent&CallBack=aHR0cDovLzgyLjE1Ny4yNi4xNTI6ODA5OS9hcGkvdjIvYWdlbnQvaW5zdGFsbC9jYWxsYmFjaz9haWQ9MTk=&Type=hosts&ClusterId=23&Roles=' | sh}
EA-SERVER-DEBUG:2022/11/25 21:05:03 client.go:98: * * * CreateWithUserPwd * * * host -> 172.21.0.15
EA-SERVER-DEBUG:2022/11/25 21:05:03 client.go:99: * * * CreateWithUserPwd * * * user -> root
EA-SERVER-DEBUG:2022/11/25 21:05:03 client.go:100: * * * CreateWithUserPwd * * * pass -> Datasphere#12345!
EA-SERVER-DEBUG:2022/11/25 21:05:03 client.go:101: * * * CreateWithUserPwd * * * port -> 22
EA-SERVER-DEBUG:2022/11/25 21:05:03 client.go:102: * * * CreateWithUserPwd * * * sshConfig -> &{{<nil> 0 [] [] []} root [0xe6fe40] 0xe6f7c0 <nil>  [] 3s}
EA-SERVER-DEBUG:2022/11/25 21:05:03 client.go:105: * * * CreateWithUserPwd * * * Dial cli -> &{0xc0003e6100 {0 {0 0}} {{0 0} []} {0 0} map[]}
EA-SERVER-DEBUG:2022/11/25 21:05:03 client.go:106: * * * CreateWithUserPwd * * * Dial err -> <nil>
EA-SERVER-DEBUG:2022/11/25 21:05:03 manage.go:78: * * * CreateWithParam * * * cli -> &{0xc0004a2a00 0xc0001ca000}
EA-SERVER-DEBUG:2022/11/25 21:05:03 manage.go:79: * * * CreateWithParam * * * err -> <nil>
EA-SERVER-DEBUG:2022/11/25 21:05:03 client.go:333: Run cmd sync:curl -s 'http://127.0.0.1:8889/api/v1/deploy/sidecar/install/shell?TargetPath=/opt/dtstack/easymanager/easyagent&CallBack=aHR0cDovLzgyLjE1Ny4yNi4xNTI6ODA5OS9hcGkvdjIvYWdlbnQvaW5zdGFsbC9jYWxsYmFjaz9haWQ9MTk=&Type=hosts&ClusterId=23&Roles=' | sh
EA-SERVER-DEBUG:2022/11/25 21:05:03 local-set.go:31: * * * [SetAssetWithLocalFile] * * * os.Args[0] -> /tmp/go-build116945771/b001/exe/main
EA-SERVER-DEBUG:2022/11/25 21:05:03 local-set.go:31: * * * [SetAssetWithLocalFile] * * * os.Args[0] -> /tmp/go-build116945771/b001/exe/main

==> easyagent-server-error.log <==
EA-SERVER-ERROR:2022/11/25 21:05:03 local-set.go:47: [InitInstallSidecarShWithLocalFile] easyagent_install.sh, err: stat /tmp/go-build116945771/b001/exe/easyagent_install.sh: no such file or directory
EA-SERVER-ERROR:2022/11/25 21:05:03 local-set.go:47: [InitInstallSidecarShWithLocalFile] easyagent_install_4win.ps1, err: stat /tmp/go-build116945771/b001/exe/easyagent_install_4win.ps1: no such file or directory

==> easyagent-server.log <==
EA-SERVER-DEBUG:2022/11/25 21:05:03 local-set.go:31: * * * [SetAssetWithLocalFile] * * * os.Args[0] -> /tmp/go-build116945771/b001/exe/main
EA-SERVER-DEBUG:2022/11/25 21:05:03 local-set.go:31: * * * [SetAssetWithLocalFile] * * * os.Args[0] -> /tmp/go-build116945771/b001/exe/main

==> easyagent-server-error.log <==

==> agent-install.log <==
agent-install2022/11/25 21:05:03 deploy.go:96: 2022-11-25 21:05:03.605550 [INSTALL] InitSidecarInstallSh success: easyagent_install.sh

==> easyagent-server.log <==
EA-SERVER-DEBUG:2022/11/25 21:05:03 deploy.go:101: * * * GetSidecarInstallShell * * * ctx -> &{0xc0002ec510 0xc0004b0400 {[]} [] 0xc00046c000 [0x924ae0] <nil> 0}
EA-SERVER-DEBUG:2022/11/25 21:05:10 client.go:335: * * * RunSync * * * out -> [+] Installing agent (easyagent sidecar)...
Stopping easyagent-sidecar
27370
Killing easyagent-sidecar (pid 27370) with SIGTERM
Waiting easyagent-sidecar (pid 27370) to die...
Waiting easyagent-sidecar (pid 27370) to die...
easyagent-sidecar stopped stopped
[+] config EasyManage agent (easyagent sidecar)...
[+] easyagent-sidecar is already installed...
[+] setting EasyManage agent (easyagent sidecar)...
Starting easyagent-sidecar
started
start easyagent success! ...
EA-SERVER-DEBUG:2022/11/25 21:05:10 client.go:336: * * * RunSync * * * err -> <nil>
EA-SERVER-DEBUG:2022/11/25 21:05:10 client.go:337: * * * RunSync * * * cmd -> curl -s 'http://127.0.0.1:8889/api/v1/deploy/sidecar/install/shell?TargetPath=/opt/dtstack/easymanager/easyagent&CallBack=aHR0cDovLzgyLjE1Ny4yNi4xNTI6ODA5OS9hcGkvdjIvYWdlbnQvaW5zdGFsbC9jYWxsYmFjaz9haWQ9MTk=&Type=hosts&ClusterId=23&Roles=' | sh
EA-SERVER-DEBUG:2022/11/25 21:05:10 client.go:342: RunSync cmd output::[+] Installing agent (easyagent sidecar)...
Stopping easyagent-sidecar
27370
Killing easyagent-sidecar (pid 27370) with SIGTERM
Waiting easyagent-sidecar (pid 27370) to die...
Waiting easyagent-sidecar (pid 27370) to die...
easyagent-sidecar stopped stopped
[+] config EasyManage agent (easyagent sidecar)...
[+] easyagent-sidecar is already installed...
[+] setting EasyManage agent (easyagent sidecar)...
Starting easyagent-sidecar
started
start easyagent success! ...
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 
* * * agent-sidecar日志* * *
AGENT-ERROR:2022/11/25 21:05:01 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:03 main.go:169: quit according to signal 'terminated'
AGENT-ERROR:2022/11/25 21:05:03 event.go:66: ReportEvent error: not register sidecar

==> agent.log <==
AGENT-DEBUG:2022/11/25 21:05:03 tc_linux.go:49: delete old tc configuration
AGENT-DEBUG:2022/11/25 21:05:10 tc_linux.go:79: initialize tc configuration
AGENT-DEBUG:2022/11/25 21:05:10 tc_linux.go:49: delete old tc configuration
AGENT-DEBUG:2022/11/25 21:05:10 monitor.go:214: start collectSystemMetrics...
AGENT-DEBUG:2022/11/25 21:05:10 monitor.go:64: start collectMetrics PID: 29420...

==> agent-error.log <==
AGENT-ERROR:2022/11/25 21:05:10 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:13 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:16 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:19 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:22 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:25 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:28 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:31 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:34 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:37 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:40 event.go:66: ReportEvent error: not register sidecar
AGENT-ERROR:2022/11/25 21:05:40 event.go:66: ReportEvent error: not register sidecar
AGENT-ERROR:2022/11/25 21:05:40 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:43 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:46 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:49 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:52 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:55 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:05:58 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:06:01 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:06:04 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:06:07 rigister.go:128: RegisterSidecar error: rpc error: code = Unknown desc = sql: no rows in result set
AGENT-ERROR:2022/11/25 21:06:10 event.go:66: ReportEvent error: not register sidecar
AGENT-ERROR:2022/11/25 21:06:10 event.go:66: ReportEvent error: not register sidecar
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

**Comment by HugoWw** [comment]
你这接入的节点是和部署的chengying在同一台机器上么，chengying服务端的配置能否发出来看下

**Comment by yrui319** [comment]
是在同一台服务器上，服务端配置如下：
matrix：example-config.yml

**Comment by yrui319** [comment]
matrix、agent-server、agent-sidecar 在同一台
matrix example-config.yml
# logger
log.dir: /tmp/matrix
log.max-logger-size: 100
log.max-logger-backups: 3
log.days-to-keep: 1

# databases
mysqldb.host: 127.0.0.1
mysqldb.port: 3306
mysqldb.user: root
mysqldb.password: DT#passw0rd2019
mysqldb.dbname: dtagent

# api
api.port: 8864
api.host:
api.static-url: http://127.0.0.1:8864

#agent
agent.host: 127.0.0.1:8889
agent.install-path: /opt/dtstack/easymanager/easyagent

#grafana
grafana-url: http://127.0.0.1:3000

# 身份校验
verify.identity: true
verify.code: false

deploy.install-path: /opt/dtstack/
---------------------------------------------------------------------
agent-server example-config.yml
# logger
log.dir: /tmp/agent-server
log.max-logger-size: 100
log.max-logger-backups: 3
log.days-to-keep: 1

publish:
http:
    host: "127.0.0.1:8864"
    uri: /api/v2/instance/%s/%s #first %s means agent_id, second %s means type
    timeout: 30s

# databases
mysqldb.host: 172.21.0.16
mysqldb.port: 3306
mysqldb.user: root
mysqldb.password: DT#passw0rd2019
mysqldb.dbname: dtagent

# api
api.port: 8889
api.host:

# rpc
rpc.port: 8890
rpc.cert:
rpc.key:

**Comment by wangqi811** [comment]
先去服务器停止agent，步骤如下：
1.登录服务器，crontab -e查看crontab任务，删除已经存在的自动拉起agent的任务；
image
2.执行脚本sh /opt/dtstack/easymanager/easyagent/easyagent.sh stop;
3.删除文件夹：rm -rf /opt/dtstack/easymanager/easyagent；
4.使用命令行的方式重新接入试一下
![image](https://user-images.githubusercontent.com/15891191/204418301-996bb064-3c58-4f0a-878d-3f346958f478.png)

**Comment by wangqi811** [comment]
> 

看下我上面的方案

**Comment by yrui319** [comment]
好的，非常感谢
