### ISSUE TITLE
如何卸载已经导入的 k8s 集群（导入已有Kubernetes集群)

### ISSUE THREAD

**Issue by botsphp** [DTStack/chengying#2]
尝试托管自建的 k3s 集群，请问如何卸载 k8s 集群中的部署。

**Comment by HugoWw** [comment]
> 尝试托管自建的 k3s 集群，目前可以看到 easyagent sidecar 已经在运行，但资源占用非常高。
> 
> ![image](https://user-images.githubusercontent.com/56063441/172356655-71dbf394-6bda-4782-9bce-3f6f64b8af2a.png)
> 
> 目前尝试删除了集群，请问如何卸载 k8s 集群中的部署。

1、集群列表->Kubernetes集群(导入已有集群)->命名空间->删除命名空间->删除镜像仓库
2、集群列表->Kubernetes集群(导入已有集群)->删除集群
