### ISSUE TITLE
tc and cgroup are not implemented

### ISSUE THREAD

**Issue by zekai-li** [DTStack/chengying#21]
官网上有描述到cgroup，但是代码中没有看到cgroup完全实现

**Comment by zekai-li** [comment]
流量控制器 tc 没有完全实现，咋们后续有开发计划吗？

**Comment by wangqi811** [comment]
> 流量控制器 tc 没有完全实现，咋们后续有开发计划吗？

近期暂时没有对流量控制器的需求，请问是碰到什么问题了吗

**Comment by zekai-li** [comment]
https://mp.weixin.qq.com/s/KG6hUrUIXyNpcBf_Vg9lNg 咋们发的datamr相关功能后续会在chengying上开源吗？如果有计划这个可是里程碑的呀
