### ISSUE TITLE
SQL注入问题

### ISSUE THREAD

**Issue by aiwocga** [DTStack/chengying#22]
延时注入触发成功。
'and(select*from(select+sleep(15))a/**/union/**/select+1)='
![dingtalkgov_qt_clipbord_pic_4](https://user-images.githubusercontent.com/39823703/208840448-d111558e-2023-4d91-a28d-58187a8135e3.png)

**Comment by wangqi811** [comment]
常见SQL注入的正则过滤已经merge到master分支了，试了下可以过滤掉你提的这个语句，手动拉代码然后重新build matrix镜像即可。
