### ISSUE TITLE
MySQL组件部署

### ISSUE THREAD

**Issue by Mr-ju** [DTStack/chengying#4]
+ agent_zip=mysql.zip
+ app_dir=/opt/dtstack/MYSQL/mysql
+ agent_bin=/opt/dtstack/MYSQL/mysql/sh
+ run_user=root
+ data_dir=
+ unzip_tmp_dir=/opt/dtstack/tmp
+ DOWNLOAD_URL=http://172.18.8.104:8864/easyagent/MYSQL/5.7.35/mysql.zip
+ trap '[ "$?" -eq 0 ] || read -p "Looks like something went wrong in step ´$STEP´"' EXIT
+ install
+ STEP='install agent'
+ echo 'Use the curl download and install Please Waiting...'
Use the curl download and install Please Waiting...
+ '[' '!' -d /opt/dtstack/tmp ']'
+ cd /opt/dtstack/tmp
+ sudo curl -L -O -s http://172.18.8.104:8864/easyagent/MYSQL/5.7.35/mysql.zip
+ install_agent
+ mkdir -p /opt/dtstack/MYSQL/mysql
+ unzip -o /opt/dtstack/tmp/mysql.zip -d /opt/dtstack/MYSQL/mysql
+ '[' '!' -f /opt/dtstack/MYSQL/mysql/sh ']'
+ echo 'cmd: /opt/dtstack/MYSQL/mysql/sh not found!'
cmd: /opt/dtstack/MYSQL/mysql/sh not found!
+ exit 1
+ '[' 1 -eq 0 ']'
+ read -p 'Looks like something went wrong in step ´install agent´'

**Comment by wangqi811** [comment]
这个产品包是从哪里下载的呀，能把schema.yml发出来看一下吗？

**Comment by Mr-ju** [comment]
parent_product_name: DTHadoop
product_name: MYSQL
product_version: 5.7.35
service:

  mysql:
    version: 5.7.35
    instance:
      cmd: ./bin/mysql.sh ${is_other}
      config_paths:
        - my.cnf
      max_replica: 1
      healthcheck:
        shell: ./health.sh ${@mysql} ${user} ${password} ${is_other}
        period: 20s
        retries: 2
      logs:
        - /data/my3306/log/alert.log
      post_deploy: ./post_deploy.sh ${user} ${password} ${repl_user} ${repl_password} ${check_num} ${is_other}
      update_recreate: true
      prometheus_port: 9104
      ha_role_cmd: ./show_mysql_state.sh ${@mysql} ${user} ${password} 2>/dev/null
    group: mysql
    config:
      user: drpeco
      password: DT@Stack#123
      encryption_mysql_password: XdVyOxV50S7MA8qMfYJJFwzHpmz0qTeiObElsfOYVcQsqjUGZEZyRW+lI76vZ/BIuHb66ac3YmAvFWJD8NOPkcWcJGdMJJK+XgVs9iIVe8NP+7hmXLR7Ah5mgI5lYqbIKQ8D82TiA5D5WuU203wUqdUARGt8s8gwLXGimoIOJjg=
      repl_user: repl
      repl_password: drpEco@123
      port: 3306
      db: metastore
      tengine_ip: 127.0.0.1
      check_num: 3
      data1_len: "10G"
      data2_len: "500M"
      interactive_timeout: 12000
      wait_timeout: 12000
      max_connections: 5000
      pid_file: "/data/my3306/run/mysqld.pid"
      basedir: "/opt/dtstack/Mysql/mysql"
      datadir: "/data/my3306/data"
      tmpdir: "/data/my3306/tmp"
      socket: "/data/my3306/run/mysql.sock"
      log_error: "/data/my3306/log/alert.log"
      log_error_verbosity: 1
      slow_query_log: 1
      long_query_time: 0.5
      log_slow_admin_statements: 1
      slow_query_log_file: "/data/my3306/log/slow.log"
      general_log: 0
      general_log_file: "/data/my3306/log/general.log"
      skip_symbolic_links: "yes"
      local_infile: 0
      character_set_server: "utf8"
      lower_case_table_names: 1
      skip_external_locking: 1
      open_files_limit: 65535
      safe_user_create: 1
      performance_schema: 0
      auto_increment_increment: 2
      auto_increment_offset: 1
      innodb_buffer_pool_size: 2G
      innodb_flush_method: "O_DIRECT"
      innodb_file_per_table: 1
      innodb_log_files_in_group: 3
      innodb_log_file_size: "256M"
      innodb_buffer_pool_instances: 4
      innodb_log_buffer_size: "32M"
      innodb_flush_log_at_trx_commit: 1
      innodb_open_files: 1024
      innodb_data_home_dir: "/data/my3306/data"
      innodb_log_group_home_dir: "/data/my3306/data"
      log_bin: "/data/my3306/log/mysql_bin"
      binlog_cache_size: "32K"
      max_binlog_cache_size: "2G"
      max_binlog_size: "512M"
      binlog_format: "ROW"
      sync_binlog: 1
      log_slave_updates: 1
      expire_logs_days: 10
      innodb_io_capacity: 200
      innodb_max_dirty_pages_pct: 75
      innodb_thread_concurrency: 16
      innodb_read_io_threads: 8
      innodb_write_io_threads: 8
      innodb_file_format: "Barracuda"
      innodb_change_buffering: "all"
      innodb_adaptive_flushing: 1
      innodb_old_blocks_time: 1000
      innodb_stats_on_metadata: 0
      innodb_use_native_aio: 0
      innodb_lock_wait_timeout: 50
      innodb_rollback_on_timeout: 0
      innodb_purge_threads: 1
      innodb_strict_mode: 1
      transaction_isolation: "READ-COMMITTED"
      innodb_autoinc_lock_mode: 1
      sql_mode: "NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES"
      relay_log: "/data/my3306/log/mysqld-relay-bin"
      relay_log_index: "/data/my3306/log/mysqld-relay-bin.index"
      master_info_file: "/data/my3306/log/master.info"
      relay_log_info_file: "/data/my3306/log/relay-log.info"
      server_id: 208
      key_buffer_size: "50M"
      myisam_sort_buffer_size: "50M"
      concurrent_insert: 2
      delayed_insert_timeout: 300
      read_rnd_buffer_size: "2M"
      sort_buffer_size: "2M"
      join_buffer_size: "2M"
      read_buffer_size: "2M"
      table_open_cache: 400
      thread_cache_size: 256
      max_user_connections: 0
      max_connect_errors: 100000
      max_allowed_packet: "128M"
      query_cache_type: 2
      query_cache_limit: "1M"
      query_cache_min_res_unit: "1K"
      query_cache_size: "200M"
      skip_name_resolve: 1
      sysdate_is_now: 1
      connect_timeout: 10
      net_read_timeout: 30
      net_write_timeout: 60
      back_log: 512
      old_passwords: 0
      is_other: "false"
      log_bin_trust_function_creators: "ON"


    mysql_slave:
      version: 5.7.35
      instance:
        cmd: ./bin/mysql.sh
        config_paths:
          - my.cnf
        max_replica: 1
        healthcheck:
          shell: ./health.sh ${@mysql_slave} ${mysql_user} ${mysql_password}
          period: 20s
          retries: 2
        logs:
          - /data/my3306/log/alert.log
        post_deploy: ./post_deploy.sh ${@mysql} ${mysql.repl_user} ${mysql.repl_password} ${mysql.user} ${mysql.password} ${check_num}
        update_recreate: true
        prometheus_port: 9104
        ha_role_cmd: ./show_mysql_state.sh ${@mysql_slave} ${mysql_user} ${mysql_password} 2>/dev/null
      group: mysql
      depends_on:
        - mysql
      config:
        mysql_host: ${@mysql}
        mysql_user: ${mysql.user}
        mysql_password: ${mysql.password}
        data1_len: "10G"
        data2_len: "500M"
        pid_file: "/data/my3306/run/mysqld.pid"
        port: 3306
        default_character_set: "utf8"
        check_num: ${mysql.check_num}
        basedir: "/opt/dtstack/Mysql/mysql_slave"
        datadir: "/data/my3306/data"
        tmpdir: "/data/my3306/tmp"
        socket: "/data/my3306/run/mysql.sock"
        log_error: "/data/my3306/log/alert.log"
        log_error_verbosity: 1
        slow_query_log: 1
        long_query_time: 0.5
        log_slow_admin_statements: 1
        slow_query_log_file: "/data/my3306/log/slow.log"
        general_log: 0
        general_log_file: "/data/my3306/log/general.log"
        skip_symbolic_links: "yes"
        local_infile: 0
        character_set_server: "utf8"
        lower_case_table_names: 1
        skip_external_locking: 1
        open_files_limit: 65535
        safe_user_create: 1
        performance_schema: 0
        max_connect_errors: 100000
        auto_increment_increment: 2
        auto_increment_offset: 1
        read_only: 1
        innodb_buffer_pool_size: "2G"
        innodb_flush_method: "O_DIRECT"
        innodb_file_per_table: 1
        innodb_log_files_in_group: 3
        innodb_log_file_size: "256M"
        innodb_buffer_pool_instances: 4
        innodb_log_buffer_size: "32M"
        innodb_flush_log_at_trx_commit: 1
        innodb_open_files: 1024
        innodb_data_home_dir: "/data/my3306/data"
        innodb_log_group_home_dir: "/data/my3306/data"
        log_bin: "/data/my3306/log/mysql_bin"
        binlog_cache_size: "32K"
        max_binlog_cache_size: "1G"
        max_binlog_size: "512M"
        binlog_format: "ROW"
        sync_binlog: 1
        log_slave_updates: 1
        expire_logs_days: 10
        innodb_io_capacity: 200
        innodb_max_dirty_pages_pct: 75
        innodb_thread_concurrency: 16
        innodb_read_io_threads: 8
        innodb_write_io_threads: 8
        innodb_file_format: "Barracuda"
        innodb_change_buffering: "all"
        innodb_adaptive_flushing: 1
        innodb_old_blocks_time: 1000
        innodb_stats_on_metadata: 0
        innodb_use_native_aio: 0
        innodb_lock_wait_timeout: 50
        innodb_rollback_on_timeout: 0
        innodb_purge_threads: 1
        innodb_strict_mode: 1
        transaction_isolation: "READ-COMMITTED"
        innodb_autoinc_lock_mode: 1
        sql_mode: "NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES"
        relay_log: "/data/my3306/log/mysqld-relay-bin"
        relay_log_index: "/data/my3306/log/mysqld-relay-bin.index"
        master_info_file: "/data/my3306/log/master.info"
        relay_log_info_file: "/data/my3306/log/relay-log.info"
        server_id: 308
        key_buffer_size: "50M"
        myisam_sort_buffer_size: "50M"
        concurrent_insert: 2
        delayed_insert_timeout: 300
        read_rnd_buffer_size: "128K"
        sort_buffer_size: "2M"
        join_buffer_size: "2M"
        read_buffer_size: "2M"
        table_open_cache: 400
        thread_cache_size: 256
        max_connections: 5000
        max_user_connections: 2000
        max_allowed_packet: "128M"
        query_cache_type: 2
        query_cache_limit: "1M"
        query_cache_min_res_unit: "1K"
        query_cache_size: "200M"
        skip_name_resolve: 1
        sysdate_is_now: 1
        connect_timeout: 10
        net_read_timeout: 30
        net_write_timeout: 60
        back_log: 512
        old_passwords: 0
        log_bin_trust_function_creators: "ON"

**Comment by wangqi811** [comment]
麻烦发一下ChengYing部署机器的操作系统和内核版本分别是什么。

**Comment by Mr-ju** [comment]
操作系统和内核版本分别CentOS Linux release 7.6.1810 (Core)，Kernel: Linux 3.10.0-957.el7.x86_64  。产品包是https://hub.fastgit.xyz/DTStack/chengying-schema.git  这个地方下载，mero编译，https://dtstack-opensource.oss-cn-hangzhou.aliyuncs.com/chengying/MYSQL_5.7.35_centos7_x86_64.tar 这个地址不能下载

**Comment by wangqi811** [comment]
方便把你打的产品包发到我邮箱嘛？我邮件给你发一个可用的包试一下，oss有点问题

**Comment by wangqi811** [comment]
wangqi@dtstack.com

**Comment by Mr-ju** [comment]
邮箱已发送

**Comment by Mr-ju** [comment]
2022-06-13T01:19:56.058819Z 0 [ERROR] Can't find error-message file '/opt/dtstack/Mysql/mysql/share/errmsg.sys'. Check error-message file location and 'lc-messages-dir' configuration directive.
 100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400 2500 2600 2700 2800 2900 3000 3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 4100 4200 4300 4400 4500 4600 4700 4800 4900 5000 5100 5200 5300 5400 5500 5600 5700 5800 5900 6000 6100 6200 6300 6400 6500 6600 6700 6800 6900 7000 7100 7200 7300 7400 7500 7600 7700 7800 7900 8000 8100 8200 8300 8400 8500 8600 8700 8800 8900 9000 9100 9200 9300 9400 9500 9600 9700 9800 9900 10000 10100 10200
 100 200 300 400 500
 100 200
 100 200
 100 200
2022-06-13T01:23:09.184392Z 0 [ERROR] Can't find error-message file '/opt/dtstack/Mysql/mysql/share/errmsg.sys'. Check error-message file location and 'lc-messages-dir' configuration directive.
2022-06-13T01:23:19.294222Z 0 [ERROR] Can't find error-message file '/opt/dtstack/Mysql/mysql/share/errmsg.sys'. Check error-message file location and 'lc-messages-dir' configuration directive.
2022-06-13T01:41:38.294233Z 0 [ERROR] Can't find error-message file '

用了你邮箱那个组件包，出现这个问题。

**Comment by wangqi811** [comment]
我们本地环境没有出现这类型的错误，你试一下cp /opt/dtstack/Mysql/mysql/share/english/errmsg.sys /opt/dtstack/Mysql/mysql/share/把文件手动拷进去，然后重新安装一下MYSQL试下

**Comment by wangqi811** [comment]
不用重新安装，在/opt/dtstack/Mysql/mysql目录下执行./post_deploy.sh drpeco DT@Stack#123 repl drpEco@123 3 false看看有没有报错。

**Comment by Mr-ju** [comment]
[root@localhost mysql]# ./post_deploy.sh drpeco DT@Stack#123 repl drpEco@123 3 false
2022-06-13T08:04:25.961484Z mysqld_safe Logging to '/data/my3306/log/alert.log'.
2022-06-13T08:04:25.987087Z mysqld_safe Starting mysqld daemon with databases from /data/my3306/data
+-----------+---------------+-------------+-------------+-------------+-------------+-------------+-----------+-------------+---------------+--------------+-----------+------------+-----------------+------------+------------+--------------+------------+-----------------------+------------------+--------------+-----------------+------------------+------------------+----------------+---------------------+--------------------+------------------+------------+--------------+------------------------+----------+------------+-------------+--------------+---------------+-------------+-----------------+----------------------+-----------------------+-------------------------------------------+------------------+-----------------------+-------------------+----------------+
| Host      | User          | Select_priv | Insert_priv | Update_priv | Delete_priv | Create_priv | Drop_priv | Reload_priv | Shutdown_priv | Process_priv | File_priv | Grant_priv | References_priv | Index_priv | Alter_priv | Show_db_priv | Super_priv | Create_tmp_table_priv | Lock_tables_priv | Execute_priv | Repl_slave_priv | Repl_client_priv | Create_view_priv | Show_view_priv | Create_routine_priv | Alter_routine_priv | Create_user_priv | Event_priv | Trigger_priv | Create_tablespace_priv | ssl_type | ssl_cipher | x509_issuer | x509_subject | max_questions | max_updates | max_connections | max_user_connections | plugin                | authentication_string                     | password_expired | password_last_changed | password_lifetime | account_locked |
+-----------+---------------+-------------+-------------+-------------+-------------+-------------+-----------+-------------+---------------+--------------+-----------+------------+-----------------+------------+------------+--------------+------------+-----------------------+------------------+--------------+-----------------+------------------+------------------+----------------+---------------------+--------------------+------------------+------------+--------------+------------------------+----------+------------+-------------+--------------+---------------+-------------+-----------------+----------------------+-----------------------+-------------------------------------------+------------------+-----------------------+-------------------+----------------+
| localhost | root          | Y           | Y           | Y           | Y           | Y           | Y         | Y           | Y             | Y            | Y         | Y          | Y               | Y          | Y          | Y            | Y          | Y                     | Y                | Y            | Y               | Y                | Y                | Y              | Y                   | Y                  | Y                | Y          | Y            | Y                      |          |            |             |              |             0 |           0 |               0 |                    0 | mysql_native_password |                                           | N                | 2022-06-13 09:23:06   |              NULL | N              |
| localhost | mysql.session | N           | N           | N           | N           | N           | N         | N           | N             | N            | N         | N          | N               | N          | N          | N            | Y          | N                     | N                | N            | N               | N                | N                | N              | N                   | N                  | N                | N          | N            | N                      |          |            |             |              |             0 |           0 |               0 |                    0 | mysql_native_password | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE | N                | 2022-06-13 09:23:06   |              NULL | Y              |
| localhost | mysql.sys     | N           | N           | N           | N           | N           | N         | N           | N             | N            | N         | N          | N               | N          | N          | N            | N          | N                     | N                | N            | N               | N                | N                | N              | N                   | N                  | N                | N          | N            | N                      |          |            |             |              |             0 |           0 |               0 |                    0 | mysql_native_password | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE | N                | 2022-06-13 09:23:06   |              NULL | Y              |
| %         | drpeco        | Y           | Y           | Y           | Y           | Y           | Y         | Y           | Y             | Y            | Y         | N          | Y               | Y          | Y          | Y            | Y          | Y                     | Y                | Y            | Y               | Y                | Y                | Y              | Y                   | Y                  | Y                | Y          | Y            | Y                      |          |            |             |              |             0 |           0 |               0 |                    0 | mysql_native_password | *87A474C62BBA498F52599C702AF8610FB6B2F4CA | N                | 2022-06-13 14:18:31   |              NULL | N              |
| %         | monitor       | Y           | Y           | Y           | Y           | Y           | Y         | Y           | Y             | Y            | Y         | N          | Y               | Y          | Y          | Y            | Y          | Y                     | Y                | Y            | Y               | Y                | Y                | Y              | Y                   | Y                  | Y                | Y          | Y            | Y                      |          |            |             |              |             0 |           0 |               0 |                    0 | mysql_native_password | *4DD910529343AED0EA535324213442D97DC86EB9 | N                | 2022-06-13 14:18:31   |              NULL | N              |
| %         | repl          | N           | N           | N           | N           | N           | N         | N           | N             | N            | N         | N          | N               | N          | N          | N            | N          | N                     | N                | N            | Y               | Y                | N                | N              | N                   | N                  | N                | N          | N            | N                      |          |            |             |              |             0 |           0 |               0 |                    0 | mysql_native_password | *AFB626338BD60242C119FC80ADCFE8D800F3BEFB | N                | 2022-06-13 14:18:31   |              NULL | N              |
+-----------+---------------+-------------+-------------+-------------+-------------+-------------+-----------+-------------+---------------+--------------+-----------+------------+-----------------+------------+------------+--------------+------------+-----------------------+------------------+--------------+-----------------+------------------+------------------+----------------+---------------------+--------------------+------------------+------------+--------------+------------------------+----------+------------+-------------+--------------+---------------+-------------+-----------------+----------------------+-----------------------+-------------------------------------------+------------------+-----------------------+-------------------+----------------+
  export MYSQL_BIN=/opt/dtstack/Mysql/mysql/bin
[root@localhost mysql]# 
这是执行结果

**Comment by wangqi811** [comment]
这个执行日志是正常的了，我邮箱发你一个我修改过的产品包，你再试一下，没问题的话可以按照我下面的步骤自己操作一下，熟悉自己出包流程，步骤如下：
1. 解压MYSQL_5.7.35.tar，然后解压mysql.zip得到mysql文件夹；
2. cd mysql进入mysql文件夹，执行cp share/english/errmsg.sys share/；
3. 然后使用./mero MYSQL_5.7.35/得到最新产品包MYSQL_5.7.35.tar.
