### ISSUE TITLE
启动不报错，却把已启动的服务给停掉了

### ISSUE THREAD

**Issue by danny-zhu** [DTStack/chengying#43]
如下图所示，部署服务的节点上agent的日志内容，没有报错信息，却把进程给kill了
![image](https://github.com/DTStack/chengying/assets/12292357/d2bd85e7-3012-4b99-a446-c2c1914bd5eb)

**Comment by wangqi811** [comment]
这个是你进程没hang住吧，当成一个脚本跑完就杀掉了

**Comment by danny-zhu** [comment]
这个start.sh脚本里面有nohup java 的命令，本身start脚本启动后就退出了
![image](https://github.com/DTStack/chengying/assets/12292357/3ac26b6c-dc5b-4687-a4f5-3a9a0da90052)
start.sh脚本里面的start方法
![image](https://github.com/DTStack/chengying/assets/12292357/0e6959ba-ec1a-49c1-b3bd-eab657e94d7b)

**Comment by danny-zhu** [comment]
> 这个是你进程没hang住吧，当成一个脚本跑完就杀掉了

把start.sh脚本里的nohup命令拷贝出来直接放进schema.yml的cmd里面可以正常运行了，感谢解答
