### ISSUE TITLE
hadoop组件部署问题

### ISSUE THREAD

**Issue by Mr-ju** [DTStack/chengying#6]
DEPRECATED: Use of this script to execute hdfs command is deprecated.
Instead use the hdfs command for it.

22/06/14 10:22:49 INFO namenode.NameNode: STARTUP_MSG: 
/************************************************************
STARTUP_MSG: Starting NameNode
STARTUP_MSG:   user = root
STARTUP_MSG:   host = localhost/127.0.0.1
STARTUP_MSG:   args = [-format, -nonInteractive]
STARTUP_MSG:   version = 2.8.5
STARTUP_MSG:   classpath = /data/hadoop_base/etc/hadoop:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/commons-configuration-1.6.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/commons-digester-1.8.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/commons-io-2.4.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/commons-lang-2.6.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/commons-logging-1.1.3.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/commons-math3-3.1.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/commons-net-3.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/curator-client-2.7.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/curator-framework-2.7.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/curator-recipes-2.7.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/gson-2.2.4.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/guava-11.0.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/hadoop-annotations-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/hadoop-auth-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/hamcrest-core-1.3.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/htrace-core4-4.0.1-incubating.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/httpclient-4.5.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/httpcore-4.4.4.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jackson-core-asl-1.9.13.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jackson-jaxrs-1.9.13.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jackson-mapper-asl-1.9.13.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jackson-xc-1.9.13.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/java-xmlbuilder-0.4.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jaxb-api-2.2.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jaxb-impl-2.2.3-1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jcip-annotations-1.0-1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jersey-core-1.9.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jersey-json-1.9.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jersey-server-1.9.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jets3t-0.9.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jettison-1.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jetty-6.1.26.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jetty-sslengine-6.1.26.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jetty-util-6.1.26.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jsch-0.1.54.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/json-smart-1.3.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jsp-api-2.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/jsr305-3.0.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/junit-4.11.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/log4j-1.2.17.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/mockito-all-1.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/netty-3.6.2.Final.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/nimbus-jose-jwt-4.41.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/paranamer-2.3.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/protobuf-java-2.5.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/servlet-api-2.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/slf4j-api-1.7.10.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/snappy-java-1.0.4.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/stax-api-1.0-2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/xmlenc-0.52.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/xz-1.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/zookeeper-3.4.6.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/activation-1.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/apacheds-i18n-2.0.0-M15.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/apacheds-kerberos-codec-2.0.0-M15.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/api-asn1-api-1.0.0-M20.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/api-util-1.0.0-M20.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/asm-3.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/avro-1.7.4.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/commons-beanutils-1.7.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/commons-beanutils-core-1.8.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/commons-cli-1.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/commons-codec-1.4.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/commons-collections-3.2.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/lib/commons-compress-1.4.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/hadoop-common-2.8.5-tests.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/hadoop-common-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/common/hadoop-nfs-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/asm-3.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/commons-cli-1.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/commons-codec-1.4.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/commons-daemon-1.0.13.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/commons-io-2.4.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/commons-lang-2.6.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/commons-logging-1.1.3.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/guava-11.0.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/hadoop-hdfs-client-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/htrace-core4-4.0.1-incubating.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/jackson-core-asl-1.9.13.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/jackson-mapper-asl-1.9.13.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/jersey-core-1.9.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/jersey-server-1.9.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/jetty-6.1.26.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/jetty-util-6.1.26.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/jsr305-3.0.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/leveldbjni-all-1.8.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/log4j-1.2.17.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/netty-3.6.2.Final.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/netty-all-4.0.23.Final.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/okhttp-2.4.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/okio-1.4.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/protobuf-java-2.5.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/servlet-api-2.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/xercesImpl-2.9.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/xml-apis-1.3.04.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/lib/xmlenc-0.52.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/hadoop-hdfs-2.8.5-tests.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/hadoop-hdfs-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/hadoop-hdfs-client-2.8.5-tests.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/hadoop-hdfs-client-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/hadoop-hdfs-native-client-2.8.5-tests.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/hadoop-hdfs-native-client-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/hdfs/hadoop-hdfs-nfs-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jersey-guice-1.9.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jersey-json-1.9.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jersey-server-1.9.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jettison-1.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jetty-6.1.26.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jetty-util-6.1.26.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/json-io-2.5.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jsr305-3.0.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/leveldbjni-all-1.8.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/log4j-1.2.17.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/netty-3.6.2.Final.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/protobuf-java-2.5.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/servlet-api-2.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/stax-api-1.0-2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/xz-1.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/zookeeper-3.4.6-tests.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/zookeeper-3.4.6.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/activation-1.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/aopalliance-1.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/asm-3.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/commons-cli-1.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/commons-codec-1.4.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/commons-collections-3.2.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/commons-compress-1.4.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/commons-io-2.4.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/commons-lang-2.6.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/commons-logging-1.1.3.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/commons-math-2.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/curator-client-2.7.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/curator-test-2.7.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/fst-2.50.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/guava-11.0.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/guice-3.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/guice-servlet-3.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jackson-core-asl-1.9.13.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jackson-jaxrs-1.9.13.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jackson-mapper-asl-1.9.13.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jackson-xc-1.9.13.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/java-util-1.9.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/javassist-3.18.1-GA.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/javax.inject-1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jaxb-api-2.2.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jaxb-impl-2.2.3-1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jersey-client-1.9.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/lib/jersey-core-1.9.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/hadoop-yarn-api-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/hadoop-yarn-applications-distributedshell-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/hadoop-yarn-applications-unmanaged-am-launcher-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/hadoop-yarn-client-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/hadoop-yarn-common-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/hadoop-yarn-registry-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/hadoop-yarn-server-applicationhistoryservice-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/hadoop-yarn-server-common-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/hadoop-yarn-server-nodemanager-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/hadoop-yarn-server-resourcemanager-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/hadoop-yarn-server-sharedcachemanager-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/hadoop-yarn-server-tests-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/hadoop-yarn-server-timeline-pluginstorage-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/yarn/hadoop-yarn-server-web-proxy-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/aopalliance-1.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/asm-3.2.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/avro-1.7.4.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/commons-compress-1.4.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/commons-io-2.4.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/guice-3.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/guice-servlet-3.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/hadoop-annotations-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/hamcrest-core-1.3.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/jackson-core-asl-1.9.13.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/jackson-mapper-asl-1.9.13.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/javax.inject-1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/jersey-core-1.9.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/jersey-guice-1.9.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/jersey-server-1.9.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/junit-4.11.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/leveldbjni-all-1.8.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/log4j-1.2.17.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/netty-3.6.2.Final.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/paranamer-2.3.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/protobuf-java-2.5.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/snappy-java-1.0.4.1.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/lib/xz-1.0.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/hadoop-mapreduce-client-app-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/hadoop-mapreduce-client-common-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/hadoop-mapreduce-client-core-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/hadoop-mapreduce-client-hs-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/hadoop-mapreduce-client-hs-plugins-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-2.8.5-tests.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/hadoop-mapreduce-client-shuffle-2.8.5.jar:/opt/dtstack/Hadoop/hadoop_pkg/share/hadoop/mapreduce/hadoop-mapreduce-examples-2.8.5.jar:/data/hadoop_base/contrib/capacity-scheduler/*.jar:/data/hadoop_base/contrib/capacity-scheduler/*.jar
STARTUP_MSG:   build = Unknown -r Unknown; compiled by 'root' on 2021-11-16T12:01Z
STARTUP_MSG:   java = 1.8.0_144
************************************************************/
22/06/14 10:22:49 INFO namenode.NameNode: registered UNIX signal handlers for [TERM, HUP, INT]
22/06/14 10:22:49 INFO namenode.NameNode: createNameNode [-format, -nonInteractive]
22/06/14 10:22:49 INFO namenode.FSEditLog: Edit logging is async:true
22/06/14 10:22:49 INFO namenode.FSNamesystem: KeyProvider: null
22/06/14 10:22:49 INFO namenode.FSNamesystem: fsLock is fair: true
22/06/14 10:22:49 INFO namenode.FSNamesystem: Detailed lock hold time metrics enabled: false
22/06/14 10:22:49 ERROR blockmanagement.DatanodeManager: error reading hosts files: 
java.io.FileNotFoundException: null (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.(FileInputStream.java:138)
	at org.apache.hadoop.util.HostsFileReader.readFileToSet(HostsFileReader.java:65)
	at org.apache.hadoop.hdfs.server.blockmanagement.HostFileManager.readFile(HostFileManager.java:78)
	at org.apache.hadoop.hdfs.server.blockmanagement.HostFileManager.refresh(HostFileManager.java:150)
	at org.apache.hadoop.hdfs.server.blockmanagement.HostFileManager.refresh(HostFileManager.java:70)
	at org.apache.hadoop.hdfs.server.blockmanagement.DatanodeManager.(DatanodeManager.java:205)
	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.(BlockManager.java:318)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.(FSNamesystem.java:758)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.(FSNamesystem.java:724)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:1103)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1567)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1694)
22/06/14 10:22:49 INFO blockmanagement.DatanodeManager: dfs.block.invalidate.limit=1000
22/06/14 10:22:49 INFO blockmanagement.DatanodeManager: dfs.namenode.datanode.registration.ip-hostname-check=false
22/06/14 10:22:49 INFO blockmanagement.BlockManager: dfs.namenode.startup.delay.block.deletion.sec is set to 000:00:00:00.000
22/06/14 10:22:49 INFO blockmanagement.BlockManager: The block deletion will start around 2022 Jun 14 10:22:49
22/06/14 10:22:49 INFO util.GSet: Computing capacity for map BlocksMap
22/06/14 10:22:49 INFO util.GSet: VM type       = 64-bit
22/06/14 10:22:49 INFO util.GSet: 2.0% max memory 981.5 MB = 19.6 MB
22/06/14 10:22:49 INFO util.GSet: capacity      = 2^21 = 2097152 entries
22/06/14 10:22:49 INFO blockmanagement.BlockManager: dfs.block.access.token.enable=false
22/06/14 10:22:49 INFO blockmanagement.BlockManager: defaultReplication         = 3
22/06/14 10:22:49 INFO blockmanagement.BlockManager: maxReplication             = 512
22/06/14 10:22:49 INFO blockmanagement.BlockManager: minReplication             = 1
22/06/14 10:22:49 INFO blockmanagement.BlockManager: maxReplicationStreams      = 2
22/06/14 10:22:49 INFO blockmanagement.BlockManager: replicationRecheckInterval = 3000
22/06/14 10:22:49 INFO blockmanagement.BlockManager: encryptDataTransfer        = false
22/06/14 10:22:49 INFO blockmanagement.BlockManager: maxNumBlocksToLog          = 1000
22/06/14 10:22:49 INFO namenode.FSNamesystem: fsOwner             = root (auth:SIMPLE)
22/06/14 10:22:49 INFO namenode.FSNamesystem: supergroup          = supergroup
22/06/14 10:22:49 INFO namenode.FSNamesystem: isPermissionEnabled = true
22/06/14 10:22:49 INFO namenode.FSNamesystem: Determined nameservice ID: ns1
22/06/14 10:22:49 INFO namenode.FSNamesystem: HA Enabled: false
22/06/14 10:22:49 WARN namenode.FSNamesystem: Configured NNs:
Nameservice :
  NN ID nn1 => /172.18.8.104:9000

22/06/14 10:22:49 ERROR namenode.FSNamesystem: FSNamesystem initialization failed.
java.io.IOException: Invalid configuration: a shared edits dir must not be specified if HA is not enabled.
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.(FSNamesystem.java:783)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.(FSNamesystem.java:724)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:1103)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1567)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1694)
22/06/14 10:22:49 INFO namenode.FSNamesystem: Stopping services started for active state
22/06/14 10:22:49 INFO namenode.FSNamesystem: Stopping services started for standby state
22/06/14 10:22:49 WARN namenode.NameNode: Encountered exception during format: 
java.io.IOException: Invalid configuration: a shared edits dir must not be specified if HA is not enabled.
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.(FSNamesystem.java:783)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.(FSNamesystem.java:724)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:1103)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1567)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1694)
22/06/14 10:22:49 ERROR namenode.NameNode: Failed to start namenode.
java.io.IOException: Invalid configuration: a shared edits dir must not be specified if HA is not enabled.
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.(FSNamesystem.java:783)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.(FSNamesystem.java:724)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:1103)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1567)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1694)
22/06/14 10:22:49 INFO util.ExitUtil: Exiting with status 1
22/06/14 10:22:49 INFO namenode.NameNode: SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down NameNode at localhost/127.0.0.1
************************************************************/

**Comment by yqhy0718** [comment]
没有在hadoop部署所在节点配置/etc/hosts

**Comment by Mr-ju** [comment]
/etc/hosts，hadoop组件是怎么配置的，我自己配置还是报这个错。

**Comment by yqhy0718** [comment]
需要将接入的主机 ip hostname映射配置到hadoop集群的机器中，类似于：
xxxx  node01
yyyy  node02
zzzz  node03
......
其中xyz分别为hadoop集群中的主机ip，node0X分别为主机ip对应的hostname
