### ISSUE TITLE
是否支持ARM架构服务器部署

### ISSUE THREAD

**Issue by Kyofin** [DTStack/chengying#7]

**Comment by wangqi811** [comment]
功能上是可以支持ARM架构服务器部署的，但是目前release的这个版本是只支持amd64，如果要支持ARM架构需要手动处理

**Comment by huzk8** [comment]
是需要自行编译吗？后续release能否考虑加入arm的包



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月24日(周五) 下午4:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DTStack/chengying] 是否支持ARM架构服务器部署 (Issue #7)




 
功能上是可以支持ARM架构服务器部署的，但是目前release的这个版本是只支持amd64，如果要支持ARM架构需要手动处理

**Comment by wangqi811** [comment]
arm芯片架构下操作系统类型也很多，后续release有这个计划的话也可能只能选择部分arm架构的操作系统支持
