### ISSUE TITLE
能否增加本地开发的文档

### ISSUE THREAD

**Issue by huzk8** [DTStack/chengying#8]
希望后续参与开源贡献，想知道如果搭建本地开发环境

**Comment by wangqi811** [comment]
欢迎参与后续开发~开发文档需要后续补充一下，可以先加入我们的开源贡献钉钉群
雅泽邀请你加入钉钉群聊ChengYing开源贡献，点击进入查看详情 https://qr.dingtalk.com/action/joingroup?code=v1,k1,c/fgljUVynqIRYDYMRT5APH4g+sD0ZthuRbJX7NU+zQ=&_dt_no_comment=1&origin=11

**Comment by huzk8** [comment]
你好，钉钉提示该群不存在或者群主未开启群可被搜索功能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月24日(周五) 下午4:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DTStack/chengying] 能否增加本地开发的文档 (Issue #8)




 
欢迎参与后续开发~开发文档需要后续补充一下，可以先加入我们的开源贡献钉钉群
 雅泽邀请你加入钉钉群聊ChengYing开源贡献，点击进入查看详情 https://qr.dingtalk.com/action/joingroup?code=v1,k1,c/fgljUVynqIRYDYMRT5APH4g+sD0ZthuRbJX7NU+zQ=&amp;_dt_no_comment=1&amp;origin=11
