### ISSUE TITLE
主机下架时，报当前无Agent停止的主机，不支持下架

### ISSUE THREAD

**Issue by lishijiang** [DTStack/chengying#9]
![image](https://user-images.githubusercontent.com/28666812/179649000-6454026f-10f1-475d-aa80-4ddfeb71a76e.png)

**Comment by wangqi811** [comment]
主机下架需要去服务器停止agent，步骤如下：
1.登录服务器，crontab -e查看crontab任务，删除已经存在的自动拉起agent的任务；
![image](https://user-images.githubusercontent.com/15891191/179649567-3885903e-3954-458f-a277-7d651d480e30.png)
2.执行脚本sh /opt/dtstack/easymanager/easyagent/easyagent.sh stop;
3.删除文件夹：rm -rf /opt/dtstack/easymanager/easyagent;
4.等待几分钟页面就会显示agent已停止，可以下架。

**Comment by lishijiang** [comment]
测试过了，可以了。
